---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-service-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_URI: "mongodb://mongodb-service:27017/cart"
  AUTH_SERVICE_URL: "http://auth-service"
  PRODUCT_SERVICE_URL: "http://product-service"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
  labels:
    app: cart-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      containers:
      - name: cart-service
        image: ecommerce/cart-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: cart-service-config
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart-service
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
