---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_URI: "mongodb://mongodb-service:27017/notification"
  EMAIL_SERVICE: "smtp"
  EMAIL_HOST: "smtp.example.com"
  EMAIL_PORT: "587"
  EMAIL_USER: "your-email-user"
  EMAIL_PASSWORD: "your-email-password"
  SMS_PROVIDER_API_KEY: "your-sms-api-key"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  labels:
    app: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification-service
        image: ecommerce/notification-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: notification-service-config
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
