---
apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  NODE_ENV: "production"
  PORT: "3000"
  DB_URI: "mongodb://mongodb-service:27017/payment"
  AUTH_SERVICE_URL: "http://auth-service"
  ORDERS_SERVICE_URL: "http://orders-service"
  STRIPE_SECRET_KEY: "replace-with-your-stripe-key"
  STRIPE_WEBHOOK_SECRET: "replace-with-your-webhook-secret"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: ecommerce/payment-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        envFrom:
        - configMapRef:
            name: payment-service-config
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
