apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: indojapcorp/voting-backend:latest
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: app-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  ports:
  - port: 5001
    targetPort: 5001
  selector:
    app: backend